ADVERBS = ['in', 'within', 'on', 'with', 'under', 'by']
AUTHORS = [
    'Sage Hardy',
    'Sophia Wilcox',
    'Elliot Henson',
    'Sheldon Orozco',
    'Casey Guzman',
    'Alexandra Barajas',
    'Terrell Phillips',
    'Darion Gamble',
    'Ignacio Meyers',
    'Izayah Welch',
    'Aydan Rush',
    'Kasey Kirby'
]
COOKING_WORDS = {
    "cooking": {
        "merge": [
            "add",
            "blend",
            "coat",
            "cover",
            "grease",
            "mix",
            "season",
            "sprinkle",
            "stuff"
        ],
        "cook": [
            "bake",
            "boil",
            "broil",
            "cook",
            "fry",
            "grill",
            "roast",
            "simmer",
            "smoke",
            "steam",
            "stew",
            "stir",
            "stir-fry"
        ],
        "clean": [
            "bone",
            "break",
            "defrost",
            "dry",
            "peel",
            "rinse",
            "soak"
        ],
        "prepare": [
            "chill",
            "chop",
            "cut",
            "dice",
            "empty",
            "grate",
            "grind",
            "halve",
            "heat",
            "knead",
            "liquidize",
            "melt",
            "mince",
            "press",
            "roll",
            "sieve",
            "slice",
            "squeeze",
            "strain",
            "thicken",
            "whisk"
        ],
        "finalize": [
            "curdle",
            "decorate",
            "glaze"
        ]
    },
    "products": [
        "apricots",
        "artichokes",
        "arugula",
        "asparagus",
        "avocados",
        "basil",
        "beets",
        "black-eyed peas",
        "blood oranges",
        "broccoli",
        "carrots",
        "cauliflower",
        "chard",
        "cherries",
        "corn",
        "cucumber",
        "eggplant",
        "fava beans",
        "fennel",
        "fiddleheads",
        "garlic",
        "figs",
        "grapefruits",
        "green onions",
        "kohlrabi",
        "kumquats",
        "medjool dates",
        "morels",
        "mushrooms",
        "navel oranges",
        "nectarines",
        "nettles",
        "lettuce",
        "okra",
        "parsley",
        "passion fruit",
        "pea beans",
        "peaches",
        "plums",
        "potatoes",
        "radish",
        "raspberries",
        "rhubarb",
        "spinach",
        "spring onions",
        "strawberries",
        "tomatoes",
        "turnips",
        "pork",
        "beef",
        "lamb",
        "goat",
        "chicken",
        "turkey",
        "duck",
        "rabbit",
        "seafood",
        "game meats",
        "marinated grilled swordfish",
        "anchovies",
        "barracuda",
        "basa",
        "bass",
        "black cod",
        "sablefish",
        "blowfish",
        "bluefish",
        "bombay duck",
        "bream",
        "brill",
        "butter fish",
        "catfish",
        "cod",
        "dogfish",
        "dorade",
        "eel",
        "flounder",
        "grouper",
        "haddock",
        "hake",
        "halibut",
        "herring",
        "ilish",
        "john dory",
        "lamprey",
        "lingcod",
        "mackerel",
        "mahi mahi",
        "monkfish",
        "mullet",
        "orange roughy",
        "parrotfish",
        "patagonian toothfish",
        "perch",
        "pike",
        "pilchard",
        "pollock",
        "pomfret",
        "pompano",
        "sablefish",
        "salmon",
        "sanddab",
        "sardine",
        "sea bass",
        "shad",
        "shark",
        "skate",
        "smelt",
        "snakehead",
        "snapper",
        "sole",
        "sprat",
        "sturgeon",
        "surimi",
        "swordfish",
        "tilapia",
        "tilefish",
        "trout",
        "tuna",
        "turbot",
        "wahoo",
        "whitefish",
        "whiting",
        "witch",
        "purified water",
        "roe",
        "caviar",
        "ikura",
        "kazunoko",
        "lumpfish roe",
        "masago",
        "shad roe",
        "tobiko",
        "shellfish",
        "crustaceans",
        "crabs",
        "craw",
        "lobsters",
        "shrimps",
        "mollusca",
        "cockle",
        "cuttlefish",
        "clam",
        "loco",
        "mussel",
        "octopus",
        "oyster",
        "periwinkle",
        "scallop",
        "squid",
        "conch",
        "nautilus"
    ]
}
